# docker compose file with services for the app, database and s3

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: docker/entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - .:/app
