services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: docker/entrypoint.sh
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    volumes:
      - .:/app
