FROM python:3.12

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install jupyterlab

COPY . ./

ENV PYTHONPATH "/app:${PYTHONPATH}"
